version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: "bash -c 'sleep 5 && npm test'"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
