version: '3'

services:
  app:
    image: forward32/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/app
    command: ["npm", "test"]
